---
upload_path: "/static/assets/images"
frontmatter_file_url_template: "/docs/assets/images"
body_file_url_template: "/docs/assets/images"
new_page_extension: html
auto_deploy: true
admin_path: "/admin"
webhook_url: 
sections:
  troubleshooting:
    default_front_matter_template: troubleshooting
  other:
    default_front_matter_template: other
  faq:
    default_front_matter_template: faq
version: 0.24.1
